szp addteam -ip team01 'Boris'                                                                    'TU Delft' 3 'DW 150.01'
szp addteam -ip team02 "B'leef"                                                                   'TU Delft' 1 'DW 150.03'
szp addteam -ip team03 'Divide_N_Conquer'                                                         'TU Delft' 1 'DW 150.05'
szp addteam -ip team04 'Doeke en Jelle'                                         'Universiteit van Amsterdam' 2 'DW 150.07'
szp addteam -ip team06 'Team Shanky'                                                              'TU Delft' 1 'DW 150.10'
szp addteam -ip team07 '42-x+kikkers'                                                             'TU Delft' 1 'DW 150.12'
szp addteam -ip team08 'In het verleden behaalde resultaten bieden WEL garantie voor de toekomst' 'TU Delft' 1 'DW 150.14'
szp addteam -ip team09 'B52 Code Bomber'                                                          'TU Delft' 1 'DW 150.16'
szp addteam -ip team10 'persistence is futile'                                                    'TU Delft' 2 'DW 150.18'
szp addteam -ip team11 "Supremum B'vo! #1"                                                        'TU Delft' 1 'DW 150.20'
szp addteam -ip team12 'The Hawx'                                                                 'TU Delft' 1 'DW 160.01'
szp addteam -ip team13 'ETV'                                                                      'TU Delft' 1 'DW 160.03'
szp addteam -ip team14 "Supremum B'vo! #2"                                                        'TU Delft' 1 'DW 160.05'
szp addteam -ip team15 'Team OrangeBottleCap'                                                     'TU Delft' 1 'DW 160.07'
szp addteam -ip team17 'Team HTTP (Hardly any Time To Prepare)'                                   'TU Delft' 1 'DW 160.10'
szp addteam -ip team18 'Atari'                                                                      'Jigsaw' 2 'DW 160.12'
szp addteam -ip team19 'Browniean Motion'                                                         'TU Delft' 2 'DW 160.16'
szp addteam -ip team20 'The Minors'                                                               'TU Delft' 1 'DW 160.14'
szp addteam -ip team21 'Programmeren kun je leren'                                                'TU Delft' 2 'DW 160.18'
szp addteam -ip team22 'De Codekloppers'                                                          'TU Delft' 1 'DW 160.20'
szp addteam -ip team23 "We're Feeling Lucky"                                                      'TU Delft' 2 'DW 160.22'
szp addteam -ip team24 'Golden power'                                                             'TU Delft' 2 'DW 160.24'
