szp addteam -ip team01 "The Rat Pack"                      'TU Delft' 1 'DW 01.150.xx'
szp addteam -ip team02 "Altijd-Error"                      'TU Delft' 1 'DW 01.150.xx'
szp addteam -ip team03 "Team Bestla"                       'TU Delft' 1 'DW 01.150.xx'
szp addteam -ip team04 "There's no place like 127.0.0.1"   'TU Delft' 1 'DW 01.150.xx'
szp addteam -ip team05 "Coon & Friends"                    'TU Delft' 1 'DW 01.150.xx'
szp addteam -ip team06 "Javanauts"                         'TU Delft' 1 'DW 01.150.xx'
szp addteam -ip team07 "Team Carry"                        'TU Delft' 1 'DW 01.150.xx'
szp addteam -ip team08 "PokerStars"                        'TU Delft' 1 'DW 01.150.xx'
szp addteam -ip team09 "IndexOutOfBounds"                  'TU Delft' 1 'DW 01.150.xx'
szp addteam -ip team10 "The BA Team"                       'TU Delft' 1 'DW 01.150.xx'