szp addteam -ip team01 'Naamloos'                          'TU Delft' 1 'DW 170.01'
szp addteam -ip team02 'VeniVediVelcro'                    'TU Delft' 1 'DW 170.03'
szp addteam -ip team03 'ASDF'                              'TU Delft' 1 'DW 170.05'
szp addteam -ip team04 "Kabel b'vo"                        'TU Delft' 1 'DW 170.07'
szp addteam -ip team05 'Team Draak'                        'TU Delft' 1 'DW 170.09'
szp addteam -ip team06 'TEAM JLEI, GG NOOBS'               'TU Delft' 1 'DW 170.10'
szp addteam -ip team07 'Wallon, Flamand en den hollander'  'TU Delft' 1 'DW 170.12'
szp addteam -ip team08 'De Codekloppers'                   'TU Delft' 1 'DW 170.15'
szp addteam -ip team09 'Team Yatagarasu'                   'TU Delft' 1 'DW 170.17'
szp addteam -ip team10 'El Presidentes'                    'TU Delft' 1 'DW 170.18'
szp addteam -ip team11 'Divide By Zero'                    'TU Delft' 1 'DW 170.19'
szp addteam -ip team12 'Robot Unicorn Attack'              'TU Delft' 1 'DW 170.21'
szp addteam -ip team13 'Awesome'                           'TU Delft' 1 'DW 170.23'
szp addteam -ip team14 'geen.opdracht5'                    'TU Delft' 1 'DW 170.25'