#!/usr/bin/python

import os
import sys

if len(sys.argv) != 2:
	print "ERROR: Wrong number of arguments"
	sys.exit(1)

hostname = sys.argv[1]
if hostname == "localhost":
	print "SYSTEEM \\(INTERN\\)",
	sys.exit(0)

# This will insert the parent directory to the path so we can import
# the settings.
sys.path.insert(0, os.path.normpath(sys.path[0]+"/.."))

from django.core.management import setup_environ
import settings

setup_environ(settings)

from django.core.exceptions import ObjectDoesNotExist
from szp.models import Team, Profile

try:
	team = Profile.objects.get(ip_address=hostname).team

	print "%s \\(%s\\)" % (team.name[:25], team.location),
except ObjectDoesNotExist:
	print "UNKNOWN"
